# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
# title: Your awesome title
title: Phylogatr
email: your-email@example.com
logo: /assets/images/logo.png 
description: >- # this means to ignore newlines until "baseurl:"
  **phylo**geographic data aggre**ga**tion and **r**epurposing 
callout: |
  Beta testing is now available by invitation only. [Launch Beta App](https://app.phylogatr.org)
cite: | # line breaks preserved
  This material is based upon work supported by the [National Science Foundation](https://www.nsf.gov/) under grant number [1910623](https://www.nsf.gov/awardsearch/showAward?AWD_ID=1910623)

url: "https://phylogatr.org" # the base hostname & protocol for your site, e.g. http://example.com
github_username: OSC

# Build settings
markdown: kramdown
theme: jekyll-theme-minimal
plugins:
  - jekyll-feed

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
